CREATE TABLE `mysqldb`.`fixtures` (
  `idfixture` INT NOT NULL,
  `idhometeam` INT NULL NOT NULL,
  `idawayteam` INT NULL NOT NULL,
  `date` CHAR(10) NULL,
  `time` CHAR(5) NULL,
  `goalshometeam` INT NULL,
  `goalsawayteam` INT NULL,
  `xgoalshometeam` DECIMAL NULL,
  `xgoalsawayteam` DECIMAL NULL,
  `shotsongoalhometeam` INT NULL,
  `shotsongoalawayteam` INT NULL,
  `shotsinsideboxhometeam` INT NULL,
  `shotsinsideboxawayteam` INT NULL,
  `totalshotshometeam` INT NULL,
  `totalshotsawayteam` INT NULL,
  `ballpossessionhometeam` CHAR(3) NULL,
  `ballpossessionawayteam` CHAR(3) NULL,
  PRIMARY KEY (`idfixture`));
